import {aiScenarios,resolveAiConfig} from '@/lib/ai-config';
import {cleanRetellAnswers,slotLabels} from '@/lib/retell';
import {questionSchema} from '@/lib/material-import';
import {z} from 'zod';
import {db,context,identity,ApiError,failure,sameOrigin} from '@/lib/server';
import {today,objectiveScore,normalizeMaterial,correct,type Material,type Settings} from '@/lib/course';
import {assessRetell,assessmentFeedback} from '@/lib/retell-ai';
export const dynamic='force-dynamic';
const question=questionSchema.extend({prompt:z.string().max(2000),options:z.array(z.string().max(500)).max(8)});
const retellConfig=z.object({stage:z.union([z.literal(1),z.literal(2),z.literal(3)]),slots:z.string().max(10000),guidedKeywords:z.string().max(10000),referenceRetell:z.string().max(20000),practiceMode:z.enum(['learning','simulation']).optional(),revisionPolicy:z.enum(['missing','teacher']).optional(),responseMode:z.enum(['text','audio']).optional()});
const cultureQuestion=z.object({id:z.string().min(1).max(80),prompt:z.string().min(1).max(1000),options:z.array(z.string().min(1).max(300)).min(2).max(6),answer:z.string().min(1).max(300)});
const cultureConfig=z.object({category:z.enum(['城市与地理','电影里的英语','歌曲与表达','小说与人物','人物故事','音乐影视','校园生活','节日文化','日常文化','地方与身份']),tagline:z.string().max(200),explore:z.string().max(5000),fastFacts:z.string().max(5000),vocabulary:z.string().max(10000),cultureNotes:z.string().max(20000),checkQuestions:z.array(cultureQuestion).max(8),expressPrompt:z.string().max(2000)});
const mat=z.object({id:z.string().max(100),title:z.string().min(1).max(150),subtitle:z.string().max(200).default(''),kind:z.enum(['阅读','听力','知识拓展','写作','视频','语法']),level:z.string().max(80).default(''),minutes:z.number().int().min(0).max(120).default(0),body:z.string().max(120000).default(''),source:z.string().max(300).default(''),sourceUrl:z.string().max(1000).refine(v=>!v||/^https:\/\//.test(v)).default(''),rights:z.string().max(1000).default(''),audio:z.string().max(200).refine(v=>!v||/^\/api\/audio\?key=[a-f0-9-]+$/.test(v)).default(''),reviewed:z.boolean(),images:z.array(z.object({url:z.string().regex(/^\/api\/media\?key=[-a-f0-9]{36}$/),caption:z.string().max(300).default('')})).max(6).optional(),video:z.string().regex(/^\/api\/media\?key=[a-f0-9-]+$/).or(z.literal('')).optional(),contentFormat:z.enum(['text','html']).optional(),grammarMode:z.enum(['choice','fill','passage']).optional(),subtitles:z.string().max(30000).optional(),playLimit:z.number().int().min(0).max(20).optional(),allowSeek:z.boolean().optional(),allowSpeed:z.boolean().optional(),explanationVisibility:z.enum(['submitted','reviewed']).optional(),completionOnly:z.boolean().optional(),retellConfig:retellConfig.optional(),cultureConfig:cultureConfig.optional(),questions:z.array(question).max(30).default([])}).superRefine((m,c)=>{
 for(const q of m.questions){if((q.audioStart===undefined)!==(q.audioEnd===undefined)||q.audioStart!==undefined&&q.audioEnd!==undefined&&q.audioEnd<=q.audioStart)c.addIssue({code:'custom',message:'听写片段需同时填写起止秒数，结束必须晚于开始'});if(q.audioStart!==undefined&&m.kind!=='听力')c.addIssue({code:'custom',message:'音频片段仅用于听力'});}
 if(new Set(m.questions.map(q=>q.id)).size!==m.questions.length)c.addIssue({code:'custom',message:'题目编号重复'});
 if(m.contentFormat==='html'&&m.kind!=='知识拓展')c.addIssue({code:'custom',message:'HTML 页面仅用于知识拓展'});
 if(m.completionOnly&&m.questions.length)c.addIssue({code:'custom',message:'仅记录完成的材料不能同时设置题目'});
 if(!m.reviewed)return;
 if(m.kind==='阅读'||m.kind==='听力'&&!m.retellConfig){
  if(!m.body.trim()||!m.questions.length||m.questions.some(q=>!q.prompt.trim()||q.options.some(o=>!o.trim())))c.addIssue({code:'custom',message:'发布前请补全正文、题干与选项'});
  if(m.questions.some(q=>!q.answer.trim()))c.addIssue({code:'custom',message:'发布前请补全答案'});
  for(const q of m.questions)if(q.type==='choice'&&(q.options.length<2||!q.options.includes(q.answer)||new Set(q.options).size!==q.options.length))c.addIssue({code:'custom',message:'选择题需至少两个不重复选项，且正确答案必须与选项一致'});
 }
 if(m.kind==='听力'&&!m.audio&&m.retellConfig?.stage!==2)c.addIssue({code:'custom',message:'听力材料需上传音频后才能发布'});
 if(m.retellConfig){if(m.kind!=='听力')c.addIssue({code:'custom',message:'转述训练配置仅用于听力'});if(!m.body.trim()||!m.retellConfig.slots.trim()||!m.retellConfig.referenceRetell.trim()||m.retellConfig.stage===2&&!m.retellConfig.guidedKeywords.trim())c.addIssue({code:'custom',message:'发布前请填写听力原文、信息槽、阶段关键词和参考转述'});if(m.questions.length!==1||m.questions[0].id!=='retell')c.addIssue({code:'custom',message:'转述训练需要一个文本作答框'});}
 if(['语法','知识拓展'].includes(m.kind)&&!m.body.trim())c.addIssue({code:'custom',message:'发布前请填写内容'});
 if(m.cultureConfig){if(m.kind!=='知识拓展')c.addIssue({code:'custom',message:'Culture Lab 配置仅用于知识拓展'});if(!m.cultureConfig.tagline.trim()||!m.cultureConfig.explore.trim()||!m.cultureConfig.cultureNotes.trim()||m.cultureConfig.checkQuestions.length<3||!m.cultureConfig.expressPrompt.trim())c.addIssue({code:'custom',message:'发布前请补全导入、文化卡片、至少三道理解题和表达任务'});for(const q of m.cultureConfig.checkQuestions)if(!q.options.includes(q.answer))c.addIssue({code:'custom',message:'Culture Lab 理解题答案必须与选项一致'});}
 if(m.kind==='视频'&&!m.video)c.addIssue({code:'custom',message:'请上传视频'});
 if(m.kind==='写作'&&(m.questions.length!==1||m.questions[0].type!=='writing'||!m.questions[0].prompt.trim()))c.addIssue({code:'custom',message:'发布前请填写写作题目'});
});
const aiScenarioSchema=z.object({enabled:z.boolean(),model:z.string().max(120),prompt:z.string().trim().min(1).max(12000)});
const aiConfigSchema=z.object({generalPrompt:z.string().trim().min(1).max(8000),temperature:z.number().min(0).max(1),maxSuggestions:z.number().int().min(1).max(6),scenarios:z.object(Object.fromEntries(Object.keys(aiScenarios).map(key=>[key,aiScenarioSchema])) as Record<keyof typeof aiScenarios,typeof aiScenarioSchema>)});
const answersSchema=z.record(z.string().max(60),z.string().max(10000));
function decoded(r:any){return {...r,answers:JSON.parse(r.answers),grades:JSON.parse(r.grades),corrections:JSON.parse(r.corrections)}}
async function state(c:any){
 const ts=await db().prepare(c.role==='teacher'?'SELECT * FROM tasks ORDER BY date DESC,created ASC':'SELECT * FROM tasks WHERE date <= ? ORDER BY date DESC,created ASC');
 const tasks=(await (c.role==='teacher'?ts:ts.bind(today())).all()).results.map((r:any)=>({...r,material:normalizeMaterial(JSON.parse(r.material))}));
 const submissions=(await (c.role==='teacher'?db().prepare('SELECT * FROM submissions ORDER BY updated DESC'):db().prepare('SELECT * FROM submissions WHERE student = ? ORDER BY updated DESC').bind(c.id)).all()).results.map(decoded);
 for(const s of submissions){const rows=(await db().prepare('SELECT question,state,data FROM assessments WHERE submission=?').bind(s.id).all()).results;for(const row of rows){const revision=row.question==='retell-revision';if(!revision&&row.question!=='retell')continue;s[revision?'revisionAssessmentState':'assessmentState']=row.state;if(row.state==='complete')s[revision?'revisionAssessment':'aiAssessment']=JSON.parse(row.data);}}
 const tagStats:Record<string,{total:number;wrong:number}>={};
 for(const s of submissions){const m=tasks.find((t:any)=>t.id===s.task)?.material;if(!m||s.state==='draft')continue;const released=c.role==='teacher'||m.explanationVisibility!=='reviewed'||s.state==='reviewed';s.unreadFeedback=!!s.feedback_updated&&s.feedback_updated!==s.feedback_read;s.workflow=m.completionOnly?'已完成':s.state!=='reviewed'||s.correction_status==='pending'?'待批改':m.questions.some((q:any)=>q.type==='writing'?s.correction_status==='required':!correct(q,s.corrections[q.id]??s.answers[q.id]))?'待订正':'已完成';if(released)for(const q of m.questions){if(q.type==='writing')continue;tagStats[q.tag]??={total:0,wrong:0};tagStats[q.tag].total++;if(!correct(q,s.answers[q.id]))tagStats[q.tag].wrong++;}}
 if(c.role==='student')for(const t of tasks){const s=submissions.find((s:any)=>s.task===t.id&&s.state!=='draft');if(!s||(t.material.explanationVisibility==='reviewed'&&s.state!=='reviewed')){t.material.subtitles='';t.material.questions=t.material.questions.map(({answer,explanation,...q}:any)=>q);if(t.material.kind==='听力')t.material.body='';if(t.material.retellConfig)t.material.retellConfig={...t.material.retellConfig,slots:slotLabels(t.material.retellConfig.slots).join('\n'),referenceRetell:'',guidedKeywords:t.material.retellConfig.stage===2?t.material.retellConfig.guidedKeywords:''}}}
 const rows=(await db().prepare('SELECT * FROM materials ORDER BY created,id').all()).results.map((r:any)=>normalizeMaterial(JSON.parse(r.data)));
 const materials=c.role==='teacher'?rows:rows.filter((m:Material)=>m.kind==='知识拓展'&&m.reviewed).map((m:Material)=>({...m,questions:[],cultureConfig:m.cultureConfig?{...m.cultureConfig,checkQuestions:m.cultureConfig.checkQuestions.map(({answer,...q})=>q)}:undefined}));
 return {role:c.role,email:c.email,userId:c.id,tagStats,settings:c.role==='teacher'?c.settings:{studentName:c.settings.studentName,textbook:c.settings.textbook,region:c.settings.region,minutes:c.settings.minutes,teacherMessage:c.settings.teacherMessage||'',teacherMessageUpdated:c.settings.teacherMessageUpdated||''},materials,tasks,submissions};
}
async function evaluateRetell(settings:Settings,m:Material,answers:Record<string,string>,id:string,revision:boolean,now:string){
 const question=revision?'retell-revision':'retell';
 await db().prepare("INSERT INTO assessments(id,submission,question,state,data,attempts,updated) VALUES(?,?,?,'running','{}',1,?) ON CONFLICT(submission,question) DO UPDATE SET state='running',attempts=attempts+1,updated=excluded.updated").bind(crypto.randomUUID(),id,question,Date.now()).run();
 if(!resolveAiConfig(settings.aiConfig).scenarios[`retell${m.retellConfig!.stage}`].enabled){await db().prepare("UPDATE assessments SET state='paused',data='{}',updated=? WHERE submission=? AND question=?").bind(Date.now(),id,question).run();return}
 try{
  const result=await assessRetell(settings,m,answers.retell,answers.retellNotes);
  const needsRevision=m.retellConfig?.revisionPolicy!=='teacher'&&(result.points?.some(p=>p.status!=='correct')||result.missingPoints.length>0);
  const status=m.retellConfig?.revisionPolicy==='teacher'?'pending':needsRevision?'required':'reviewed',feedback=(revision?'订正反馈（首次成绩保留）\n':'')+assessmentFeedback(result,m.retellConfig?.stage),version=now+'-'+crypto.randomUUID();
  const update=revision?db().prepare("UPDATE submissions SET state='reviewed',feedback=?,feedback_updated=?,correction_status=?,updated=? WHERE id=?").bind(feedback,version,status,now,id):db().prepare("UPDATE submissions SET state='reviewed',score=?,total=100,feedback=?,grades=?,feedback_updated=?,correction_status=?,updated=? WHERE id=?").bind(result.score,feedback,JSON.stringify({retell:result.score}),version,status,now,id);
  await db().batch([db().prepare("UPDATE assessments SET state='complete',data=?,updated=? WHERE submission=? AND question=?").bind(JSON.stringify(result),Date.now(),id,question),update]);
 }catch{
  await db().prepare("UPDATE assessments SET state='failed',data='{}',updated=? WHERE submission=? AND question=?").bind(Date.now(),id,question).run();
 }
}
export async function GET(){try{const c=await context();return Response.json(await state(c),{headers:{'Cache-Control':'no-store'}})}catch(e){return failure(e)}}
export async function POST(req:Request){try{sameOrigin(req);if(Number(req.headers.get('content-length')||0)>250000)throw new ApiError('内容过大');const p=z.object({op:z.string()}).passthrough().parse(await req.json());const c=await context();const now=new Date().toISOString();
if(['teacherMessage','settings','aiSettings','material','reviewMaterial','assign','grade','unpublish'].includes(p.op)&&c.role!=='teacher')throw new ApiError('此操作仅限老师。',403);
if(p.op==='readFeedback'){if(c.role!=='student')throw new ApiError('仅学生可以标记反馈已读',403);const v=z.object({id:z.string(),version:z.string().min(1)}).parse(p);await db().prepare('UPDATE submissions SET feedback_read=? WHERE id=? AND student=? AND feedback_updated=?').bind(v.version,v.id,c.id,v.version).run();}
else if(p.op==='teacherMessage'){const message=z.string().trim().max(5000).parse(p.message);await db().prepare('UPDATE settings SET data=? WHERE id=1').bind(JSON.stringify({...c.settings,aiApiKey:c.settings.aiApiKey,teacherMessage:message,teacherMessageUpdated:now})).run();}
else if(p.op==='settings'){const s=z.object({studentEmail:z.union([z.literal(''),z.string().email()]),studentName:z.string().min(1).max(60),textbook:z.string().min(1).max(100),region:z.string().min(1).max(100),minutes:z.number().int().min(5).max(120)}).parse(p.settings);s.studentEmail=s.studentEmail.toLowerCase();if(s.studentEmail===c.email)throw new ApiError('学生账号不能与老师账号相同');if(c.settings!.studentId&&s.studentEmail!==c.settings!.studentEmail)throw new ApiError('学生已绑定账号，不能更换邮箱，以保留作业归属。');await db().prepare('UPDATE settings SET data = ? WHERE id = 1').bind(JSON.stringify({...c.settings,...s,aiApiKey:c.settings.aiApiKey,studentId:c.settings!.studentId,studentUsername:c.settings!.studentUsername})).run();}
else if(p.op==='aiSettings'){const s=z.object({aiBaseUrl:z.string().url().max(500).refine(v=>/^https:\/\//.test(v)||/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?(?:\/|$)/.test(v),'API 地址必须使用 HTTPS，本机服务可使用 HTTP'),aiModel:z.string().min(1).max(120),aiApiKey:z.string().max(500).optional(),aiConfig:aiConfigSchema.optional()}).parse(p.settings);const key=s.aiApiKey?.trim()||c.settings.aiApiKey;if(!key)throw new ApiError('请填写 API 密钥');await db().prepare('UPDATE settings SET data=? WHERE id=1').bind(JSON.stringify({...c.settings,aiBaseUrl:s.aiBaseUrl.replace(/\/+$/,''),aiModel:s.aiModel,aiConfig:s.aiConfig??c.settings.aiConfig,aiApiKey:key,aiConfigured:undefined})).run();}
else if(p.op==='material'){const m=mat.parse(p.material);if(m.reviewed&&m.retellConfig&&!c.settings.aiApiKey)throw new ApiError('请先在“AI评测设置”中配置 API');if(!m.id)m.id=crypto.randomUUID();await db().prepare('INSERT INTO materials (id,data,created) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').bind(m.id,JSON.stringify(m),now).run();}
else if(p.op==='reviewMaterial'){const r=await db().prepare('SELECT data FROM materials WHERE id = ?').bind(String(p.id)).first();if(!r)throw new ApiError('材料不存在',404);const m=mat.parse({...normalizeMaterial(JSON.parse(r.data)),reviewed:true});await db().prepare('UPDATE materials SET data = ? WHERE id = ?').bind(JSON.stringify(m),m.id).run();}
else if(p.op==='assign'){const x=z.object({ids:z.array(z.string()).min(1).max(14),dates:z.array(z.string().regex(/^\d{4}-\d{2}-\d{2}$/)).min(1).max(7),note:z.string().max(1500)}).parse(p);const statements=[];for(const date of [...new Set(x.dates)]){if(isNaN(Date.parse(date))||new Date(date).toISOString().slice(0,10)!==date)throw new ApiError('日期无效');for(const id of [...new Set(x.ids)]){const r=await db().prepare('SELECT data FROM materials WHERE id = ?').bind(id).first();if(!r)throw new ApiError('材料不存在');const m=mat.parse(normalizeMaterial(JSON.parse(r.data)));if(!m.reviewed)throw new ApiError('请先审核全部所选材料');statements.push(db().prepare('INSERT INTO tasks (id,date,material,note,created) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),date,JSON.stringify(m),x.note,now));}}await db().batch(statements);}
else if(p.op==='unpublish'){const count=await db().prepare('SELECT (SELECT count(*) FROM submissions WHERE task = ?) + (SELECT count(*) FROM annotations WHERE task = ?) AS n').bind(String(p.id),String(p.id)).first();if(count.n)throw new ApiError('已有作答或批注记录，不能撤回');await db().batch([db().prepare('DELETE FROM listens WHERE task = ?').bind(String(p.id)),db().prepare('DELETE FROM tasks WHERE id = ?').bind(String(p.id))]);}
else if(p.op==='retryRetell'){
 if(c.role!=='student')throw new ApiError('仅学生可重试评测',403);
 const row=await db().prepare('SELECT s.*,t.material FROM submissions s JOIN tasks t ON t.id=s.task WHERE s.task=? AND s.student=?').bind(String(p.task),c.id).first();
 if(!row||row.state==='draft')throw new ApiError('请先提交作业');
 const m=JSON.parse(row.material) as Material;if(!m.retellConfig)throw new ApiError('不是转述练习');
 const corrections=JSON.parse(row.corrections),revision=!!corrections.retell,question=revision?'retell-revision':'retell';
 const assessment=await db().prepare('SELECT state,updated FROM assessments WHERE submission=? AND question=?').bind(row.id,question).first();
 if(!assessment||assessment.state!=='failed'&&assessment.state!=='paused'&&!(assessment.state==='running'&&Date.now()-assessment.updated>60000))throw new ApiError('当前无需重试，请刷新查看反馈',409);
 await evaluateRetell(c.settings,m,revision?corrections:JSON.parse(row.answers),row.id,revision,now);
}
else if(['draft','submit','correct'].includes(p.op)){if(c.role!=='student')throw new ApiError('老师预览不会写入学生成绩。',403);const r=await db().prepare('SELECT * FROM tasks WHERE id = ? AND date <= ?').bind(String(p.task),today()).first();if(!r)throw new ApiError('作业尚未开放或不存在',404);const m=JSON.parse(r.material) as Material;const a=answersSchema.parse(p.answers);
 if(m.retellConfig&&a.retellNotes){
  let notes;try{notes=z.array(z.object({text:z.string().max(300),status:z.enum(['noted','unsure','missed'])})).max(100).parse(JSON.parse(a.retellNotes))}catch{throw new ApiError('笔记格式无效，请刷新后恢复草稿再试')}
  if(p.op!=='draft'&&m.retellConfig.stage!==2&&(notes.length!==slotLabels(m.retellConfig.slots).length||notes.some(n=>!n.text.trim()&&n.status!=='missed')))throw new ApiError('请记录每项要点，未听到的项目请标记“没听到”');
  a.retellNotes=JSON.stringify(notes);
 }
 const clean=cleanRetellAnswers(m,a);const old=await db().prepare('SELECT * FROM submissions WHERE task = ? AND student = ?').bind(r.id,c.id).first();if(old){const running=await db().prepare("SELECT updated FROM assessments WHERE submission=? AND state='running'").bind(old.id).first();if(running&&Date.now()-running.updated<60000)throw new ApiError('正在评测，请稍后再提交',409);}if(p.op==='correct'){if(!old||old.state==='draft')throw new ApiError('请先提交作业');if(m.questions.some(q=>!clean[q.id].trim()))throw new ApiError('请完成全部订正答案');await db().prepare("UPDATE submissions SET corrections = ?, updated = ?, correction_status = ? WHERE id = ?").bind(JSON.stringify(clean),now,m.questions.some(q=>q.type==='writing')?'pending':'reviewed',old.id).run();if(m.retellConfig)await evaluateRetell(c.settings,m,clean,old.id,true,now);}
else {if(old&&old.state!=='draft')throw new ApiError('作业已提交，首次作答已保留，请使用订正。',409);if(p.op==='submit'&&m.questions.some(q=>!clean[q.id].trim()))throw new ApiError('请完成全部题目后提交');const {score,total}=objectiveScore(m,clean),state=p.op==='draft'?'draft':m.completionOnly?'reviewed':'submitted',submissionId=old?.id||crypto.randomUUID();await db().prepare("INSERT INTO submissions (id,task,student,answers,state,score,total,feedback,grades,corrections,submitted,updated) VALUES (?,?,?,?,?,?,?,'','{}','{}',?,?) ON CONFLICT(task,student) DO UPDATE SET answers=excluded.answers,state=excluded.state,score=excluded.score,total=excluded.total,submitted=excluded.submitted,updated=excluded.updated WHERE submissions.state='draft'").bind(submissionId,r.id,c.id,JSON.stringify(clean),state,score,total,p.op==='submit'?now:null,now).run();if(p.op==='submit'&&m.retellConfig)await evaluateRetell(c.settings,m,clean,submissionId,false,now);}}
else if(p.op==='grade'){const r=await db().prepare('SELECT s.*,t.material FROM submissions s JOIN tasks t ON t.id=s.task WHERE s.id = ?').bind(String(p.id)).first();if(!r||r.state==='draft')throw new ApiError('没有可批改的提交');const m=JSON.parse(r.material) as Material;const grades=z.record(z.number().int().min(0).max(100)).parse(p.grades);for(const q of m.questions.filter(q=>q.type==='writing'))if(grades[q.id]===undefined||grades[q.id]>(q.maxScore||1))throw new ApiError('请为所有主观题评分，且不超过本题满分');const requestRevision=z.boolean().optional().parse(p.requestRevision)||false;const feedback=z.string().max(5000).parse(p.feedback);await db().prepare("UPDATE submissions SET state='reviewed',feedback=?,grades=?,updated=?,feedback_updated=?,correction_status=? WHERE id=?").bind(feedback,JSON.stringify(grades),now,now+'-'+crypto.randomUUID(),requestRevision?'required':'reviewed',r.id).run();}
else throw new ApiError('未知操作');return Response.json({ok:true});}catch(e){if(e instanceof z.ZodError)return Response.json({error:'请检查填写内容：'+e.issues.map(i=>i.message).join('；')},{status:400});return failure(e)}}
