import {questionSchema} from '@/lib/material-import';
import {z} from 'zod';
import {db,context,identity,ApiError,failure,sameOrigin} from '@/lib/server';
import {today,objectiveScore,normalizeMaterial,correct,type Material,type Settings} from '@/lib/course';
export const dynamic='force-dynamic';
const question=questionSchema.extend({prompt:z.string().max(2000),options:z.array(z.string().max(500)).max(8)});
const mat=z.object({id:z.string().max(100),title:z.string().min(1).max(150),subtitle:z.string().max(200),kind:z.enum(['阅读','听力','知识拓展','写作','视频','语法']),level:z.string().min(1).max(80),minutes:z.number().int().min(1).max(120),body:z.string().max(120000),source:z.string().min(1).max(300),sourceUrl:z.string().max(1000).refine(v=>!v||/^https:\/\//.test(v)),rights:z.string().min(1).max(1000),audio:z.string().max(200).refine(v=>!v||/^\/api\/audio\?key=[a-f0-9-]+$/.test(v)),reviewed:z.boolean(),video:z.string().regex(/^\/api\/media\?key=[a-f0-9-]+$/).or(z.literal('')).optional(),contentFormat:z.enum(['text','html']).optional(),grammarMode:z.enum(['choice','fill','passage']).optional(),subtitles:z.string().max(30000).optional(),playLimit:z.number().int().min(0).max(20).optional(),allowSeek:z.boolean().optional(),allowSpeed:z.boolean().optional(),explanationVisibility:z.enum(['submitted','reviewed']).optional(),completionOnly:z.boolean().optional(),questions:z.array(question).max(30)}).superRefine((m,c)=>{for(const q of m.questions){if((q.audioStart===undefined)!==(q.audioEnd===undefined)||q.audioStart!==undefined&&q.audioEnd!==undefined&&q.audioEnd<=q.audioStart)c.addIssue({code:'custom',message:'听写片段需同时填写起止秒数，结束必须晚于开始'});if(q.audioStart!==undefined&&m.kind!=='听力')c.addIssue({code:'custom',message:'音频片段仅用于听力'});}if(new Set(m.questions.map(q=>q.id)).size!==m.questions.length)c.addIssue({code:'custom',message:'题目编号重复'});for(const q of m.questions)if(q.type==='choice'&&m.reviewed&&(q.options.length<2||(!!q.answer&&!q.options.includes(q.answer))||new Set(q.options).size!==q.options.length))c.addIssue({code:'custom',message:'选择题需至少两个不重复选项，且正确答案必须与选项一致'});if(m.reviewed){if(!m.body.trim()||m.questions.some(q=>!q.prompt.trim()||q.options.some(o=>!o.trim())))c.addIssue({code:'custom',message:'审核前请补全正文、题干与选项'});if(!m.completionOnly&&!m.questions.length)c.addIssue({code:'custom',message:'请添加题目或选择仅记录完成'});if(m.questions.some(q=>!q.answer.trim()))c.addIssue({code:'custom',message:'审核前请补全答案或评分要求'});if(m.kind==='视频'&&!m.video)c.addIssue({code:'custom',message:'请上传视频'});if(m.kind==='语法'&&m.grammarMode==='choice'&&m.questions.some(q=>q.type!=='choice'))c.addIssue({code:'custom',message:'语法选择材料请使用选择题'});if(m.kind==='语法'&&m.grammarMode==='fill'&&m.questions.some(q=>q.type!=='fill'))c.addIssue({code:'custom',message:'语法填空材料请使用填空题'});}if(m.contentFormat==='html'&&m.kind!=='知识拓展')c.addIssue({code:'custom',message:'HTML 页面仅用于知识拓展'});if(m.completionOnly&&m.questions.length)c.addIssue({code:'custom',message:'仅记录完成的材料不能同时设置题目'});if(m.reviewed&&m.kind==='听力'&&!m.audio)c.addIssue({code:'custom',message:'听力材料需上传音频后才能通过审核'})});
const answersSchema=z.record(z.string().max(60),z.string().max(10000));
function decoded(r:any){return {...r,answers:JSON.parse(r.answers),grades:JSON.parse(r.grades),corrections:JSON.parse(r.corrections)}}
async function state(c:any){const ts=await db().prepare(c.role==='teacher'?'SELECT * FROM tasks ORDER BY date DESC,created ASC':'SELECT * FROM tasks WHERE date <= ? ORDER BY date DESC,created ASC');const tasks=(await (c.role==='teacher'?ts:ts.bind(today())).all()).results.map((r:any)=>({...r,material:normalizeMaterial(JSON.parse(r.material))}));const submissions=(await (c.role==='teacher'?db().prepare('SELECT * FROM submissions ORDER BY updated DESC'):db().prepare('SELECT * FROM submissions WHERE student = ? ORDER BY updated DESC').bind(c.id)).all()).results.map(decoded);const tagStats:Record<string,{total:number;wrong:number}>={};for(const s of submissions){const m=tasks.find((t:any)=>t.id===s.task)?.material;if(!m||s.state==='draft')continue;const released=c.role==='teacher'||m.explanationVisibility!=='reviewed'||s.state==='reviewed';s.unreadFeedback=!!s.feedback_updated&&s.feedback_updated!==s.feedback_read;s.workflow=s.state!=='reviewed'||s.correction_status==='pending'?'待批改':m.questions.some((q:any)=>q.type==='writing'?s.correction_status==='required':!correct(q,s.corrections[q.id]??s.answers[q.id]))?'待订正':'已完成';if(released)for(const q of m.questions){if(q.type==='writing')continue;tagStats[q.tag]??={total:0,wrong:0};tagStats[q.tag].total++;if(!correct(q,s.answers[q.id]))tagStats[q.tag].wrong++;}}if(c.role==='student')for(const t of tasks){const s=submissions.find((s:any)=>s.task===t.id&&s.state!=='draft');if(!s||(t.material.explanationVisibility==='reviewed'&&s.state!=='reviewed')){t.material.subtitles='';t.material.questions=t.material.questions.map(({answer,explanation,...q}:any)=>q);if(t.material.kind==='听力')t.material.body=''}}return {role:c.role,email:c.email,userId:c.id,tagStats,settings:c.role==='teacher'?c.settings:{studentName:c.settings.studentName,textbook:c.settings.textbook,region:c.settings.region,minutes:c.settings.minutes},materials:c.role==='teacher'?(await db().prepare('SELECT * FROM materials ORDER BY created,id').all()).results.map((r:any)=>normalizeMaterial(JSON.parse(r.data))):[],tasks,submissions}}
export async function GET(){try{const c=await context();return Response.json(await state(c),{headers:{'Cache-Control':'no-store'}})}catch(e){return failure(e)}}
export async function POST(req:Request){try{sameOrigin(req);if(Number(req.headers.get('content-length')||0)>250000)throw new ApiError('内容过大');const p=z.object({op:z.string()}).passthrough().parse(await req.json());const c=await context();const now=new Date().toISOString();
if(['settings','material','reviewMaterial','assign','grade','unpublish'].includes(p.op)&&c.role!=='teacher')throw new ApiError('此操作仅限老师。',403);
if(p.op==='readFeedback'){if(c.role!=='student')throw new ApiError('仅学生可以标记反馈已读',403);const v=z.object({id:z.string(),version:z.string().min(1)}).parse(p);await db().prepare('UPDATE submissions SET feedback_read=? WHERE id=? AND student=? AND feedback_updated=?').bind(v.version,v.id,c.id,v.version).run();}
else if(p.op==='settings'){const s=z.object({studentEmail:z.union([z.literal(''),z.string().email()]),studentName:z.string().min(1).max(60),textbook:z.string().min(1).max(100),region:z.string().min(1).max(100),minutes:z.number().int().min(5).max(120)}).parse(p.settings);s.studentEmail=s.studentEmail.toLowerCase();if(s.studentEmail===c.email)throw new ApiError('学生账号不能与老师账号相同');if(c.settings!.studentId&&s.studentEmail!==c.settings!.studentEmail)throw new ApiError('学生已绑定账号，不能更换邮箱，以保留作业归属。');await db().prepare('UPDATE settings SET data = ? WHERE id = 1').bind(JSON.stringify({...s,studentId:c.settings!.studentId,studentUsername:c.settings!.studentUsername})).run();}
else if(p.op==='material'){const m=mat.parse(p.material);if(!m.id)m.id=crypto.randomUUID();await db().prepare('INSERT INTO materials (id,data,created) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').bind(m.id,JSON.stringify(m),now).run();}
else if(p.op==='reviewMaterial'){const r=await db().prepare('SELECT data FROM materials WHERE id = ?').bind(String(p.id)).first();if(!r)throw new ApiError('材料不存在',404);const m=mat.parse({...normalizeMaterial(JSON.parse(r.data)),reviewed:true});await db().prepare('UPDATE materials SET data = ? WHERE id = ?').bind(JSON.stringify(m),m.id).run();}
else if(p.op==='assign'){const x=z.object({ids:z.array(z.string()).min(1).max(14),dates:z.array(z.string().regex(/^\d{4}-\d{2}-\d{2}$/)).min(1).max(7),note:z.string().max(1500)}).parse(p);const statements=[];for(const date of [...new Set(x.dates)]){if(isNaN(Date.parse(date))||new Date(date).toISOString().slice(0,10)!==date)throw new ApiError('日期无效');for(const id of [...new Set(x.ids)]){const r=await db().prepare('SELECT data FROM materials WHERE id = ?').bind(id).first();if(!r)throw new ApiError('材料不存在');const m=mat.parse(normalizeMaterial(JSON.parse(r.data)));if(!m.reviewed)throw new ApiError('请先审核全部所选材料');statements.push(db().prepare('INSERT INTO tasks (id,date,material,note,created) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),date,JSON.stringify(m),x.note,now));}}await db().batch(statements);}
else if(p.op==='unpublish'){const count=await db().prepare('SELECT (SELECT count(*) FROM submissions WHERE task = ?) + (SELECT count(*) FROM annotations WHERE task = ?) AS n').bind(String(p.id),String(p.id)).first();if(count.n)throw new ApiError('已有作答或批注记录，不能撤回');await db().batch([db().prepare('DELETE FROM listens WHERE task = ?').bind(String(p.id)),db().prepare('DELETE FROM tasks WHERE id = ?').bind(String(p.id))]);}
else if(['draft','submit','correct'].includes(p.op)){if(c.role!=='student')throw new ApiError('老师预览不会写入学生成绩。',403);const r=await db().prepare('SELECT * FROM tasks WHERE id = ? AND date <= ?').bind(String(p.task),today()).first();if(!r)throw new ApiError('作业尚未开放或不存在',404);const m=JSON.parse(r.material) as Material;const a=answersSchema.parse(p.answers);const clean=Object.fromEntries(m.questions.map(q=>[q.id,a[q.id]||'']));const old=await db().prepare('SELECT * FROM submissions WHERE task = ? AND student = ?').bind(r.id,c.id).first();if(p.op==='correct'){if(!old||old.state==='draft')throw new ApiError('请先提交作业');if(m.questions.some(q=>!clean[q.id].trim()))throw new ApiError('请完成全部订正答案');await db().prepare("UPDATE submissions SET corrections = ?, updated = ?, correction_status = ? WHERE id = ?").bind(JSON.stringify(clean),now,m.questions.some(q=>q.type==='writing')?'pending':'reviewed',old.id).run();}
else {if(old&&old.state!=='draft')throw new ApiError('作业已提交，首次作答已保留，请使用订正。',409);if(p.op==='submit'&&m.questions.some(q=>!clean[q.id].trim()))throw new ApiError('请完成全部题目后提交');const {score,total}=objectiveScore(m,clean);await db().prepare("INSERT INTO submissions (id,task,student,answers,state,score,total,feedback,grades,corrections,submitted,updated) VALUES (?,?,?,?,?,?,?,'','{}','{}',?,?) ON CONFLICT(task,student) DO UPDATE SET answers=excluded.answers,state=excluded.state,score=excluded.score,total=excluded.total,submitted=excluded.submitted,updated=excluded.updated WHERE submissions.state='draft'").bind(old?.id||crypto.randomUUID(),r.id,c.id,JSON.stringify(clean),p.op==='draft'?'draft':'submitted',score,total,p.op==='submit'?now:null,now).run();}}
else if(p.op==='grade'){const r=await db().prepare('SELECT s.*,t.material FROM submissions s JOIN tasks t ON t.id=s.task WHERE s.id = ?').bind(String(p.id)).first();if(!r||r.state==='draft')throw new ApiError('没有可批改的提交');const m=JSON.parse(r.material) as Material;const grades=z.record(z.number().int().min(0).max(100)).parse(p.grades);for(const q of m.questions.filter(q=>q.type==='writing'))if(grades[q.id]===undefined||grades[q.id]>(q.maxScore||1))throw new ApiError('请为所有主观题评分，且不超过本题满分');const requestRevision=z.boolean().optional().parse(p.requestRevision)||false;const feedback=z.string().max(5000).parse(p.feedback);await db().prepare("UPDATE submissions SET state='reviewed',feedback=?,grades=?,updated=?,feedback_updated=?,correction_status=? WHERE id=?").bind(feedback,JSON.stringify(grades),now,now+'-'+crypto.randomUUID(),requestRevision?'required':'reviewed',r.id).run();}
else throw new ApiError('未知操作');return Response.json({ok:true});}catch(e){if(e instanceof z.ZodError)return Response.json({error:'请检查填写内容：'+e.issues.map(i=>i.message).join('；')},{status:400});return failure(e)}}
