import {z} from 'zod';
import {db,ApiError,failure,sameOrigin} from '@/lib/storage';
import {currentAccount,requireAccount,ownerProof,hashPassword,checkPassword,issueSession,sessionTokenHash,clearCookie,limitLogin,type Account} from '@/lib/auth';
import {seeds} from '@/lib/seed';
export const dynamic='force-dynamic';
const username=z.string().trim().toLowerCase().regex(/^[a-z0-9][a-z0-9_.-]{2,31}$/,'用户名需为 3–32 位字母、数字、点、下划线或短横线');
const password=z.string().min(12,'密码至少 12 位，可使用容易记住的长句').max(128,'密码最多 128 位');
const credentials=z.object({username,password});
function reply(data:unknown,cookie?:string){return Response.json(data,{headers:{'Cache-Control':'no-store',...(cookie?{'Set-Cookie':cookie}:{})}})}
export async function GET(){try{const a=await currentAccount();const t=await db().prepare("SELECT id FROM accounts WHERE role='teacher'").first();return reply({authenticated:!!a,user:a?{username:a.username,role:a.role}:null,hasTeacher:!!t,canBootstrap:!!await ownerProof()})}catch(e){return failure(e)}}
export async function POST(req:Request){try{sameOrigin(req);const text=await req.text();if(text.length>8000)throw new ApiError('请求内容过长');const p=z.object({op:z.string()}).passthrough().parse(JSON.parse(text));const now=new Date().toISOString();
if(p.op==='login'){if(await currentAccount())throw new ApiError('请先退出当前账号，再登录其他账号。',409);const v=credentials.parse(p);await limitLogin(v.username);const a=await db().prepare('SELECT * FROM accounts WHERE username=?').bind(v.username).first() as Account|null;if(!checkPassword(v.password,a))throw new ApiError('用户名或密码不正确。',401);return reply({ok:true},await issueSession(a!.id));}
if(p.op==='logout'){const token=await sessionTokenHash();if(token)await db().prepare('DELETE FROM sessions WHERE token_hash=?').bind(token).run();return reply({ok:true},clearCookie());}
if(p.op==='setupTeacher'){const owner=await ownerProof();if(!owner)throw new ApiError('仅网站所有者可以初始化老师账号。',403);const v=credentials.parse(p);const existing=await db().prepare("SELECT id FROM accounts WHERE role='teacher'").first();if(existing)throw new ApiError('老师账号已创建，请登录。',409);const row=await db().prepare('SELECT * FROM settings WHERE id=1').first();const hash=hashPassword(v.password);const commands=[db().prepare("INSERT INTO accounts (id,username,role,password_hash,created) VALUES (?,?,'teacher',?,?)").bind(owner.id,v.username,hash,now)];if(!row){commands.push(db().prepare('INSERT INTO settings (id,owner,data) VALUES (1,?,?)').bind(owner.id,JSON.stringify({studentEmail:'',studentName:'同学',textbook:'待设置',region:'待设置',minutes:20})));for(const m of seeds)commands.push(db().prepare('INSERT INTO materials (id,data,created) VALUES (?,?,?)').bind(m.id,JSON.stringify(m),now))}await db().batch(commands);return reply({ok:true},await issueSession(owner.id));}
const a=await requireAccount();
if(p.op==='changePassword'){const v=z.object({currentPassword:z.string().max(128),password}).parse(p);await limitLogin(a.username);if(!checkPassword(v.currentPassword,a))throw new ApiError('当前密码不正确',401);const hash=hashPassword(v.password);await db().batch([db().prepare('UPDATE accounts SET password_hash=? WHERE id=?').bind(hash,a.id),db().prepare('DELETE FROM sessions WHERE account_id=?').bind(a.id)]);return reply({ok:true},await issueSession(a.id));}
if(p.op==='saveStudent'){if(a.role!=='teacher')throw new ApiError('仅老师可以管理学生账号',403);const v=credentials.extend({teacherPassword:z.string().max(128)}).parse(p);await limitLogin(a.username);if(!checkPassword(v.teacherPassword,a))throw new ApiError('老师密码不正确',401);if(v.username===a.username)throw new ApiError('学生用户名不能与老师相同');const row=await db().prepare('SELECT data FROM settings WHERE id=1').first();if(!row)throw new ApiError('教学设置尚未完成');const settings=JSON.parse(row.data);const student=await db().prepare("SELECT id FROM accounts WHERE role='student'").first();const id=student?.id||settings.studentId||crypto.randomUUID();settings.studentId=id;settings.studentUsername=v.username;const hash=hashPassword(v.password);await db().batch([db().prepare("INSERT INTO accounts (id,username,role,password_hash,created) VALUES (?,?,'student',?,?) ON CONFLICT(id) DO UPDATE SET username=excluded.username,password_hash=excluded.password_hash").bind(id,v.username,hash,now),db().prepare('UPDATE settings SET data=? WHERE id=1').bind(JSON.stringify(settings)),db().prepare('DELETE FROM sessions WHERE account_id=?').bind(id)]);return reply({ok:true});}
throw new ApiError('未知操作');
}catch(e){if(e instanceof z.ZodError)return replyError(e.issues[0].message);if(e instanceof SyntaxError)return replyError('请求格式不正确');return failure(e)}}
function replyError(error:string){return Response.json({error},{status:400,headers:{'Cache-Control':'no-store'}})}
