'use client';
import {useState} from 'react';
import {Check,FlaskConical,RotateCcw,Sparkles,Settings2} from 'lucide-react';
import {aiScenarios,resolveAiConfig,type AiScenario,type AiConfig} from '@/lib/ai-config';
import type {Settings} from '@/lib/course';
type Payload={aiBaseUrl:string;aiModel:string;aiApiKey?:string;aiConfig:AiConfig};
export function AiSettingsForm({settings,busy,onSave}:{settings:Settings;busy:boolean;onSave:(value:Payload)=>Promise<boolean>}){
 const [connection,setConnection]=useState({aiBaseUrl:settings.aiBaseUrl||'https://api.openai.com/v1',aiModel:settings.aiModel||'',aiApiKey:''});
 const [config,setConfig]=useState(()=>resolveAiConfig(settings.aiConfig)),[active,setActive]=useState<AiScenario>('retell1'),[testing,setTesting]=useState(false),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false);
 const selected=config.scenarios[active],locked=busy||testing;
 function changeConfig(value:AiConfig){setConfig(value);setDirty(true);setMessage('')}
 function updateScenario(p:Partial<typeof selected>){changeConfig({...config,scenarios:{...config.scenarios,[active]:{...selected,...p}}})}
 return <><div className="page-heading"><div><div className="kicker">AI WORKSPACE</div><h1>AI 配置中心</h1><p>统一管理模型连接、教学要求与每个场景的提示词。</p></div><span className={'tag '+(settings.aiConfigured?'green':'neutral')}>{settings.aiConfigured?'接口已配置':'待配置接口'}</span></div>
 <form className="ai-settings-layout" onSubmit={async e=>{e.preventDefault();if(await onSave({...connection,aiConfig:config})){setConnection({...connection,aiApiKey:''});setDirty(false);setMessage('已保存。后续 AI 请求将使用这份配置，已有评测不会改变。')}}}>
 <section className="panel ai-connection"><h2><Settings2 size={20}/> 模型连接</h2><p className="helper">适用于所有场景；单个场景可覆盖模型名称。</p><div className="form-grid"><label>API 地址<input required type="url" maxLength={500} value={connection.aiBaseUrl} onChange={e=>{setConnection({...connection,aiBaseUrl:e.target.value});setDirty(true)}}/></label><label>默认模型<input required maxLength={120} value={connection.aiModel} placeholder="服务商提供的模型 ID" onChange={e=>{setConnection({...connection,aiModel:e.target.value});setDirty(true)}}/></label></div><label>API 密钥<input type="password" maxLength={500} autoComplete="new-password" value={connection.aiApiKey} placeholder={settings.aiConfigured?'已安全保存；留空保留原密钥':'填写 API 密钥'} onChange={e=>{setConnection({...connection,aiApiKey:e.target.value});setDirty(true)}}/></label><p className="helper">密钥仅保存在服务器，不发送到学生端。接口需支持 Chat Completions 与 JSON 输出。</p></section>
 <section className="panel"><h2>通用教学要求</h2><label>所有场景共用的要求<textarea rows={3} required maxLength={8000} value={config.generalPrompt} onChange={e=>changeConfig({...config,generalPrompt:e.target.value})}/></label><div className="form-grid"><label>生成随机性（0–1）<input type="number" min={0} max={1} step={0.1} value={config.temperature} onChange={e=>changeConfig({...config,temperature:Number(e.target.value)})}/><small>评测建议保持在 0–0.3。</small></label><label>优先改进建议数量<input type="number" min={1} max={6} value={config.maxSuggestions} onChange={e=>changeConfig({...config,maxSuggestions:Number(e.target.value)})}/></label></div></section>
 <section className="panel ai-prompt-panel"><div className="section-heading"><div><h2><Sparkles size={20}/> 场景与提示词</h2><p className="helper">教学要求可以编辑；答案隔离、输出格式和分数范围由系统保证。</p></div></div><div className="ai-prompt-workspace"><nav aria-label="AI 场景">{Object.entries(aiScenarios).map(([key,v])=><button type="button" key={key} className={key===active?'active':''} aria-pressed={key===active} onClick={()=>setActive(key as AiScenario)}><b>{v.title}</b><small>{config.scenarios[key as AiScenario].enabled?'已启用':'已暂停'}</small></button>)}</nav><div className="ai-prompt-editor"><h3>{aiScenarios[active].title}</h3><p>{aiScenarios[active].description}</p><label className="inline-check"><input type="checkbox" checked={selected.enabled} onChange={e=>updateScenario({enabled:e.target.checked})}/>启用此场景</label><label>场景模型（可选）<input maxLength={120} value={selected.model} placeholder="留空使用默认模型" onChange={e=>updateScenario({model:e.target.value})}/></label><label>教学提示词<textarea required rows={9} maxLength={12000} value={selected.prompt} onChange={e=>updateScenario({prompt:e.target.value})}/></label><button type="button" className="btn secondary" onClick={()=>updateScenario({prompt:aiScenarios[active].prompt})}><RotateCcw size={16}/>恢复本场景默认提示词</button><p className="helper">材料、参考答案、学生答案会自动附带，无须填写变量。暂停听力评测后，学生答案仍保存，交由老师批改。</p></div></div></section>
 <footer className="settings-actions"><span role="status">{message|| (dirty?'有未保存的更改':'配置已同步') }</span><div><button className="btn secondary" type="button" disabled={locked||dirty||!settings.aiConfigured||!selected.enabled} onClick={async()=>{setTesting(true);setMessage('正在测试已保存的场景配置…');try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op:'test',scenario:active})}),d=await r.json();if(!r.ok)throw Error(d.error);setMessage(d.message)}catch(e){setMessage((e as Error).message)}finally{setTesting(false)}}}><FlaskConical size={17}/>{testing?'测试中…':'测试当前场景'}</button><button className="btn" disabled={locked} type="submit"><Check size={18}/>{busy?'保存中…':'保存全部 AI 设置'}</button></div></footer>
 </form></>;
}
