'use client';
import {useEffect,useState} from 'react';
import {toast} from 'sonner';
import {SafeHtml} from './safe-html';
import {Button} from './daily-app';
import type {Material} from '@/lib/course';

const steps=['Explore','Learn','Check','Express','Complete'] as const;
type Progress={steps:string[];answers:Record<string,string>;expression:string;score:number;status:string;answered:number;total:number;results?:Record<string,boolean>};
const empty:Progress={steps:[],answers:{},expression:'',score:0,status:'未开始',answered:0,total:0,results:{}};
async function request(material:string,body?:unknown){const r=await fetch(body?'/api/culture':'/api/culture?material='+encodeURIComponent(material),body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'暂时无法保存');return d.progress}

export function CultureLab({material,teacher=false}:{material:Material;teacher?:boolean}){
 const cfg=material.cultureConfig!,[step,setStep]=useState(0),[progress,setProgress]=useState<Progress>(empty),[answers,setAnswers]=useState<Record<string,string>>({}),[expression,setExpression]=useState(''),[busy,setBusy]=useState(false),[checked,setChecked]=useState(false);
 useEffect(()=>{if(!teacher)request(material.id).then(p=>{if(p){setProgress(p);setAnswers(p.answers||{});setExpression(p.expression||'')}}).catch(e=>toast.error(e.message))},[material.id,teacher]);
 async function save(kind:'explore'|'learn'|'check'|'express',next=true){if(teacher){if(kind==='check'){const results=Object.fromEntries(cfg.checkQuestions.map(q=>[q.id,answers[q.id]===q.answer]));const score=Math.round(Object.values(results).filter(Boolean).length/Math.max(1,cfg.checkQuestions.length)*100);setProgress(p=>({...p,score,results}));setChecked(true)}if(kind==='express')setProgress(p=>({...p,status:p.score>=80?'已完成':'学习中'}));if(next)setStep(x=>Math.min(4,x+1));return}setBusy(true);try{const p=await request(material.id,{material:material.id,step:kind,answers:kind==='check'?answers:undefined,expression:kind==='express'?expression:undefined});setProgress(p);if(kind==='check')setChecked(true);if(next)setStep(x=>Math.min(4,x+1))}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 const facts=cfg.fastFacts.split('\n').map(x=>x.trim()).filter(Boolean),notes=cfg.cultureNotes.split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean),vocab=cfg.vocabulary.split('\n').map(x=>x.split('|').map(y=>y.trim())).filter(x=>x[0]);
 return <div className="culture-lab">{teacher&&<p className="helper">教师预览 · 可以试做，不保存学生学习记录。</p>}<header className="culture-hero"><span>{cfg.category}</span><h2>{material.title}</h2><p>{cfg.tagline}</p></header><nav className="culture-steps" aria-label="文化学习步骤">{steps.map((name,i)=><button key={name} className={i===step?'active':progress.status==='已完成'||progress.steps.includes(['explore','learn','check','express','complete'][i])?'done':''} aria-current={i===step?'step':undefined} onClick={()=>setStep(i)}><b>{i<4?i+1:'★'}</b>{name}</button>)}</nav>
 {step===0&&<section className="culture-stage"><div className="culture-stage-title"><span>01</span><div><small>BUILD BACKGROUND</small><h3>Explore · 认识主题</h3></div></div><div className="reading-text">{cfg.explore}</div>{facts.length>0&&<div className="culture-facts">{facts.map((fact,i)=><article key={i}><b>FAST FACT {i+1}</b><p>{fact}</p></article>)}</div>}<div className="culture-actions"><Button disabled={busy} onClick={()=>save('explore')}>开始学习 →</Button></div></section>}
 {step===1&&<section className="culture-stage"><div className="culture-stage-title"><span>02</span><div><small>LANGUAGE & CULTURE</small><h3>Learn · 阅读与文化</h3></div></div>{vocab.length>0&&<details className="culture-vocabulary"><summary>本页重点词汇 · {vocab.length}</summary>{vocab.map((v,i)=><p key={i}><b>{v[0]}</b>{v[1]&&<> · {v[1]}</>}{v[2]&&<small>{v[2]}</small>}</p>)}</details>}<SafeHtml html={material.body}/>{notes.length>0&&<div className="culture-notes">{notes.map((note,i)=>{const [title,...body]=note.split('\n');return <article key={i}><small>CULTURE NOTE {String(i+1).padStart(2,'0')}</small><h4>{title}</h4><p>{body.join('\n')}</p></article>})}</div>}<div className="culture-actions"><Button disabled={busy} onClick={()=>save('learn')}>完成阅读，开始检测 →</Button></div></section>}
 {step===2&&<section className="culture-stage"><div className="culture-stage-title"><span>03</span><div><small>CHECK UNDERSTANDING</small><h3>Check · 理解检测</h3></div></div><p className="helper">全部作答且正确率达到 80%，才能完成本主题。</p>{cfg.checkQuestions.map((q,i)=><fieldset className="culture-question" key={q.id}><legend><span>{String(i+1).padStart(2,'0')}</span>{q.prompt}</legend>{q.options.map(o=><label key={o} className={answers[q.id]===o?'selected':''}><input type="radio" name={q.id} checked={answers[q.id]===o} onChange={()=>{setAnswers({...answers,[q.id]:o});setChecked(false)}}/>{o}</label>)}{checked&&answers[q.id]&&<small className={progress.results?.[q.id]?'success-text':'error-text'}>{progress.results?.[q.id]?'回答正确':'再读一读相关内容'}</small>}</fieldset>)}{checked&&<div className="culture-score"><strong>{progress.score}%</strong><span>{progress.score>=80?'理解检测已通过':'还差一点，可以修改后再次提交'}</span></div>}<div className="culture-actions"><Button disabled={busy||cfg.checkQuestions.some(q=>!answers[q.id])} onClick={()=>save('check',false)}>{busy?'正在保存…':'提交检测'}</Button>{checked&&progress.score>=80&&<Button secondary onClick={()=>setStep(3)}>进入表达任务 →</Button>}</div></section>}
 {step===3&&<section className="culture-stage"><div className="culture-stage-title"><span>04</span><div><small>USE YOUR ENGLISH</small><h3>Express · 表达观点</h3></div></div><div className="culture-prompt"><b>YOUR TASK</b><p>{cfg.expressPrompt}</p></div><label>用英语写下你的想法<textarea rows={8} maxLength={10000} value={expression} onChange={e=>setExpression(e.target.value)} placeholder="Use simple and complete English sentences..."/></label><div className="culture-actions"><Button disabled={busy||!expression.trim()} onClick={()=>save('express')}>{busy?'正在保存…':'提交表达 →'}</Button></div></section>}
 {step===4&&<section className="culture-stage culture-complete"><span className="culture-complete-mark">{progress.status==='已完成'?'★':'○'}</span><small>CULTURE TOPIC</small><h3>{progress.status==='已完成'?'Topic Completed':'还差一步'}</h3><h2>{material.title}</h2><p>{progress.status==='已完成'?`${cfg.category} · 理解检测 ${progress.score}%`:'完成理解检测（≥80%）和英语表达任务后，即可完成本主题。'}</p>{progress.status!=='已完成'&&<Button onClick={()=>setStep(progress.score>=80?3:2)}>继续学习</Button>}</section>}
 </div>;
}
