
'use client';
import {useState,useEffect,useRef} from 'react';
import {Play,Pause,Headphones} from 'lucide-react';
import {ListeningImages} from './listening-images';
import {AnnotatedText} from './annotations-ui';
import {SafeHtml} from './safe-html';
import {Button,Choice} from './daily-app';
import {correct,type Task,type Question} from '@/lib/course';
async function request(url:string,body?:unknown){const r=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const d:any=await r.json();if(!r.ok)throw Error(d.error||'暂时无法完成');return d}
export function LessonAudio({task,sample}:{task:Task;sample:boolean}){
 const m=task.material.retellConfig?.practiceMode==='learning'?{...task.material,playLimit:0,allowSeek:true,allowSpeed:true}:task.material,ref=useRef<HTMLAudioElement>(null),blob=useRef(''),lock=useRef(false),end=useRef<number|undefined>(undefined);
 const [busy,setBusy]=useState(false),[active,setActive]=useState(false),[paused,setPaused]=useState(false),[count,setCount]=useState(0),[extra,setExtra]=useState(0),[time,setTime]=useState(0),[duration,setDuration]=useState(0),[speed,setSpeed]=useState('1×'),[error,setError]=useState(''),[label,setLabel]=useState('整篇音频'),[startAt,setStartAt]=useState(0);
 useEffect(()=>{if(!sample)request('/api/listen?task='+encodeURIComponent(task.id)).then(d=>{setCount(d.count);setExtra(d.extra)}).catch(e=>setError(e.message));return()=>{if(blob.current)URL.revokeObjectURL(blob.current)}},[task.id,sample]);
 function finish(){ref.current?.pause();setActive(false);setPaused(false)}
 async function start(q?:Question,index?:number){if(lock.current)return;lock.current=true;setBusy(true);setError('');finish();try{const a=ref.current;if(!a)return;let src=m.audio;if(!sample){const d=await request('/api/listen',{task:task.id});setCount(d.count);setExtra(d.extra);const r=await fetch(d.url);if(!r.ok)throw Error('音频加载失败');if(blob.current)URL.revokeObjectURL(blob.current);blob.current=URL.createObjectURL(await r.blob());src=blob.current}await new Promise<void>((resolve,reject)=>{a.onloadedmetadata=()=>resolve();a.onerror=()=>reject(Error('音频无法播放'));a.src=src;a.load()});if(q?.audioEnd!==undefined&&q.audioEnd>a.duration+.2)throw Error('片段时间超出音频长度，请联系老师核对');const begin=q?.audioStart||0;end.current=q?.audioEnd;setStartAt(begin);setDuration(a.duration);setLabel(q?'第 '+((index||0)+1)+' 题片段':'整篇音频');a.currentTime=begin;a.playbackRate=parseFloat(speed);await a.play();setActive(true);setPaused(false)}catch(e){setError((e as Error).message+'；若已扣次数但没有听到，请联系老师补充。')}finally{lock.current=false;setBusy(false)}}
 if(m.retellConfig?.stage===2)return null;
 const disabled=busy||!m.audio||(!sample&&!!m.playLimit&&count>=m.playLimit+extra);
 return <section className="lesson-audio-bar" aria-label="听力播放器"><div className="audio-main"><b><Headphones size={20}/>{label}</b><span className="helper">{sample?'老师试听':m.playLimit?`已开始 ${count}/${m.playLimit+extra} 次`:`已开始 ${count} 次 · 不限`}</span><audio ref={ref} onTimeUpdate={()=>{const a=ref.current;if(!a)return;setTime(a.currentTime);if(end.current!==undefined&&a.currentTime>=end.current)finish()}} onEnded={finish}/>{active&&<Button secondary disabled={busy} onClick={()=>{if(paused)ref.current?.play().then(()=>setPaused(false)).catch(()=>setError('播放未成功，请再次点击继续'));else{ref.current?.pause();setPaused(true)}}}>{paused?<Play size={18}/>:<Pause size={18}/>} {paused?'继续播放':'暂停'}</Button>}<Button className="audio-play-primary" disabled={disabled} onClick={()=>start()}><Play size={19}/>{busy?'正在加载…':count?'重新播放':'开始听音频'}</Button><span className="helper">{Math.floor(time)} / {Math.floor(duration)||0} 秒</span></div><progress className="audio-timeline" aria-label="音频播放进度" value={time} max={Number.isFinite(duration)&&duration>0?duration:1}/><div className="audio-clips">{m.questions.map((q,i)=>q.audioStart!==undefined&&q.audioEnd!==undefined?<Button secondary key={q.id} disabled={disabled} onClick={()=>start(q,i)}>第 {i+1} 题 · {q.audioStart}–{q.audioEnd} 秒</Button>:null)}</div><details><summary>播放设置与次数说明</summary><p className="helper">每次开始整篇或片段均计 1 次，暂停后继续不计次。片段到结束位置自动暂停。</p>{m.allowSeek&&active&&<label>进度<input aria-label="播放进度" type="range" min={startAt} max={end.current??(Number.isFinite(duration)?duration:0)} value={time} onChange={e=>{if(ref.current)ref.current.currentTime=Number(e.target.value)}}/></label>}{m.allowSpeed&&<Choice label="播放速度" value={speed} items={['0.8×','1×','1.2×']} onChange={v=>{setSpeed(v);if(ref.current)ref.current.playbackRate=parseFloat(v)}}/>}</details>{error&&<p role="alert" className="error-text">{error}</p>}</section>
}
export function LessonMedia({task,sample,revealed}:{task:Task;sample:boolean;revealed:boolean}){const m=task.material,c=m.retellConfig;return <><h2 className="paper-article-title">{m.title}</h2><ListeningImages material={m}/>{m.kind==='视频'&&m.video&&<video className="lesson-video" controls playsInline preload="metadata" src={m.video}/>} {m.kind==='听力'?c&&!revealed&&!sample?<div className="reading-text"><h3>{c.stage===1?'阶段一 · 听懂并记要点':c.stage===2?'阶段二 · 看要点组织表达':'阶段三 · 听后独立转述'}</h3><p>{c.stage===1?'听音频并按下面的信息项记录关键词，不必写完整句。':c.stage===2?'根据题目中给出的关键词，用自己的语言完成英语转述。':'听音频、记录关键词，再完成完整英语转述。'}</p>{c.stage!==2&&<><b>这次要听出的信息</b><p>{c.slots.split('\n').map(x=>x.split(':')[0]).filter(Boolean).join(' · ')}</p></>}</div>:(revealed||sample)&&m.body?<details open><summary>听力原文</summary><div className="reading-text"><AnnotatedText text={m.body} section="body"/></div></details>:<p className="helper">听音频并完成重点句。原文按老师设置，在提交后或批改后开放。</p>:m.body&&(m.kind==='知识拓展'&&m.contentFormat==='html'?<SafeHtml html={m.body} annotatable/>:<div className="reading-text"><AnnotatedText text={m.body} section="body"/></div>)}{m.subtitles&&(sample||revealed)&&<details><summary>字幕文本</summary><div className="reading-text">{m.subtitles}</div></details>}</>}
export function DictationDiff({q,answer}:{q:Question;answer:string}){if(!q.strict||!q.answer)return null;if(correct(q,answer))return <p>逐词核对通过。</p>;const norm=(s:string)=>{if(!q.caseSensitive)s=s.toLowerCase();if(!q.punctuationSensitive)s=s.replace(/[\p{P}]/gu,'');return s};const expected=q.answer.split('|')[0].trim().split(/\s+/),actual=answer.trim().split(/\s+/);if(expected.length>300||actual.length>300)return <p>请逐句对照参考原文。</p>;const dp=Array.from({length:expected.length+1},()=>Array(actual.length+1).fill(0));for(let i=expected.length;i>=0;i--)for(let j=actual.length;j>=0;j--){if(i===expected.length)dp[i][j]=actual.length-j;else if(j===actual.length)dp[i][j]=expected.length-i;else dp[i][j]=norm(expected[i])===norm(actual[j])?dp[i+1][j+1]:1+Math.min(dp[i+1][j],dp[i][j+1],dp[i+1][j+1])}const parts=[];let i=0,j=0;while(i<expected.length||j<actual.length){if(i<expected.length&&j<actual.length&&norm(expected[i])===norm(actual[j])){parts.push(<span key={parts.length}>{actual[j]} </span>);i++;j++}else if(i<expected.length&&j<actual.length&&dp[i][j]===1+dp[i+1][j+1]){parts.push(<mark key={parts.length}>错：{actual[j]} → {expected[i]} </mark>);i++;j++}else if(i<expected.length&&dp[i][j]===1+dp[i+1][j]){parts.push(<mark key={parts.length}>漏：{expected[i]} </mark>);i++}else{parts.push(<del key={parts.length}>多：{actual[j]} </del>);j++}}return <div className="dictation-diff"><small>与第一条参考答案逐词对照：</small><p>{parts}</p></div>}
