'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
type Message={id:number;author:'teacher'|'student';body:string;created:string;read_at:string|null};
type Page={messages:Message[];hasOlder:boolean;unread:number};
async function request(body?:unknown,before?:number){const r=await fetch('/api/messages'+(before?'?before='+before:''),body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error||'留言加载失败');return data as Page;}
export function MessageBoard({role}:{role:'teacher'|'student'}){
 const [messages,setMessages]=useState<Message[]>([]),[hasOlder,setHasOlder]=useState(false),[unread,setUnread]=useState(0),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[loaded,setLoaded]=useState(false);
 const initialLoaded=useRef(false);
 const load=useCallback(async(before?:number)=>{const page=await request(undefined,before);setMessages(old=>[...new Map([...old,...page.messages].map(m=>[m.id,m])).values()].sort((a,b)=>a.id-b.id));setUnread(page.unread);if(before||!initialLoaded.current)setHasOlder(page.hasOlder);initialLoaded.current=true;setLoaded(true);setError('');},[]);
 useEffect(()=>{let active=true;const refresh=()=>{if(active&&document.visibilityState==='visible')load().catch(e=>{if(active)setError(e.message)})};refresh();const timer=setInterval(refresh,30000);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return ()=>{active=false;clearInterval(timer);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh)}},[load]);
 async function send(){if(busy||!draft.trim())return;setBusy(true);setError('');setStatus('');try{await request({op:'send',body:draft});setDraft('');setStatus('留言已发送。');await load();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function read(){if(!messages.length)return;setBusy(true);try{await request({op:'read',through:messages[messages.length-1].id});await load();setStatus('已标记为已读。')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel message-board" aria-label="师生留言板"><div className="section-heading"><h2>师生留言板</h2>{unread>0&&<span className="tag">{unread} 条未读</span>}</div><p className="helper">{role==='student'?'今天有事无法完成任务，或学习中有疑问，都可以在这里告诉老师。':'查看学生的任务说明与问题，也可以在这里回复。'} 留言会保留，双方都能查看，最新留言显示在前。</p>
 {hasOlder&&<button className="text-link" disabled={busy} onClick={()=>{setBusy(true);load(messages[0]?.id).catch(e=>setError(e.message)).finally(()=>setBusy(false))}}>查看更早留言</button>}
 <div className="message-history" tabIndex={0} aria-label="留言记录">{!loaded?<p className="helper">正在加载留言…</p>:!messages.length?<p className="helper">还没有留言，从这里开始沟通吧。</p>:messages.slice().reverse().map(m=><article key={m.id} className={'message-item '+(m.author===role?'message-mine':'')}><div><b>{m.author==='teacher'?'老师':'学生'}{m.author===role?'（我）':''}</b><time dateTime={m.created}>{new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(m.created))}</time></div><p>{m.body}</p>{m.author===role&&<small className="helper">{m.read_at?'对方已读':'待对方查看'}</small>}</article>)}</div>
 {unread>0&&<button className="text-link" disabled={busy} onClick={read}>将当前留言标为已读</button>}
 <form onSubmit={e=>{e.preventDefault();void send()}}><label htmlFor="message-draft">{role==='student'?'给老师留言':'回复学生'}<textarea id="message-draft" value={draft} rows={3} maxLength={2000} disabled={busy} onChange={e=>{setDraft(e.target.value);setStatus('')}} placeholder={role==='student'?'例如：今天有事，无法完成练习，我会明天补上。':'写下你的回复或学习建议。'}/></label><div className="message-actions"><small className="helper">{draft.length}/2000</small><button className="btn" type="submit" disabled={busy||!draft.trim()}>{busy?'正在处理…':'发送留言'}</button></div></form>{error&&<p role="alert" className="error-text">{error}</p>}{status&&<p role="status" className="success-text">{status}</p>}</section>
}
