'use client';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {ArrowLeft,ArrowUp,ArrowDown,Check,Bookmark,Highlighter,Type,Send} from 'lucide-react';
import {AnnotationProvider,AnnotatedText,useAnnotations} from './annotations-ui';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {correct,type CourseData,type Submission,type Task} from '@/lib/course';

async function api(body?:unknown):Promise<CourseData>{const r=await fetch('/api/course',body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'暂时无法保存，请重试');return d}
function ReaderTools({size,onSize,onRead}:{size:number;onSize:()=>void;onRead:()=>void}){
 const {rows,edit}=useAnnotations(),[panel,setPanel]=useState<'help'|'saved'|null>(null);
 return <><nav className="reader-tools" aria-label="阅读工具"><button className="active" onClick={()=>{onRead();setPanel(null)}}>阅读</button><button onClick={onSize} aria-label={`调整字号，当前 ${size} 像素`}><Type size={17}/><span>字号</span></button><button aria-expanded={panel==='help'} onClick={()=>setPanel(panel==='help'?null:'help')}><Highlighter size={17}/><span>划线</span></button><button aria-expanded={panel==='saved'} onClick={()=>setPanel(panel==='saved'?null:'saved')}><Bookmark size={17}/><span>收藏</span></button></nav>{panel&&<aside className="reader-tool-popover" aria-label={panel==='help'?'划线帮助':'本篇收藏'}><div className="section-heading"><b>{panel==='help'?'边读边记':'本篇标记与收藏'}</b><button onClick={()=>setPanel(null)} aria-label="关闭阅读工具面板">×</button></div>{panel==='help'?<p>选中正文中的单词或句子，使用出现的“划线”或“收藏 / 批注”按钮。点击已有标记可以修改。</p>:rows.length?<ul>{rows.map(row=><li key={row.id}><button onClick={()=>edit(row)}>{row.text}<small>{row.note||'点击查看或添加批注'}</small></button></li>)}</ul>:<p>还没有标记。选中正文中的文字，收藏值得积累的表达。</p>}</aside>}</>;
}

export function ReadingPractice({task,sample,initial,onClose,onRefresh,page=false,userId=''}:{task:Task;sample:boolean;initial?:Submission;onClose:()=>void;onRefresh:()=>Promise<void>;page?:boolean;userId?:string}){
 const [material,setMaterial]=useState(task.material),[sub,setSub]=useState(initial),[answers,setAnswers]=useState<Record<string,string>>(sample?{}:{...initial?.answers,...initial?.corrections});
 const [submitted,setSubmitted]=useState(!sample&&!!initial&&initial.state!=='draft'),[revision,setRevision]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(sample?'老师试做，不保存成绩':'草稿自动保存');
 const [index,setIndex]=useState(0),[expanded,setExpanded]=useState(false),[size,setSize]=useState(22),[recovery,setRecovery]=useState<{answers:Record<string,string>;mode:string}|null>(null);
 const latest=useRef(answers),dirty=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null),queue=useRef(Promise.resolve()),article=useRef<HTMLElement>(null),dragY=useRef<number|null>(null),dragged=useRef(false);
 const key=`ed-draft:${userId}:${task.id}`,reviewing=submitted&&!revision,done=material.questions.filter(q=>answers[q.id]?.trim()).length;
 useEffect(()=>{if(sample||!userId)return;try{const value=JSON.parse(localStorage.getItem(key)||'null');if(value&&value.at>Date.parse(initial?.updated||'1970-01-01')&&(!submitted||value.mode==='correction'))setRecovery(value)}catch{}},[key,sample]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty.current){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>{window.removeEventListener('beforeunload',warn);if(timer.current)clearTimeout(timer.current)}},[]);
 function clear(){try{localStorage.removeItem(key)}catch{}}
 function cache(value:Record<string,string>){if(sample)return;try{localStorage.setItem(key,JSON.stringify({answers:value,mode:revision?'correction':'draft',at:Date.now()}))}catch{setSaved('本机备份不可用，请保存草稿')}}
 async function save(value=latest.current){if(sample||revision)return;setSaved('正在保存…');const next=queue.current.catch(()=>{}).then(async()=>{await api({op:'draft',task:task.id,answers:value});if(latest.current===value){dirty.current=false;clear();setSaved('草稿已保存')}});queue.current=next;try{await next}catch(e){setSaved('保存失败，请重试');throw e}}
 function change(id:string,value:string){const next={...latest.current,[id]:value};latest.current=next;setAnswers(next);dirty.current=true;cache(next);if(timer.current)clearTimeout(timer.current);if(!sample&&!revision)timer.current=setTimeout(()=>{save(next).catch(()=>{})},900);else setSaved(sample?'老师试做，不保存成绩':'订正已在本机备份，请提交');}
 async function refresh(){const data=await api();setSub(data.submissions.find(s=>s.task===task.id));const t=data.tasks.find(t=>t.id===task.id);if(t)setMaterial(t.material);await onRefresh()}
 async function submit(){const missing=material.questions.findIndex(q=>!latest.current[q.id]?.trim());if(missing!==-1){setIndex(missing);setExpanded(false);setError(`请先完成第 ${missing+1} 题。`);return}setError('');if(sample){setSubmitted(true);setExpanded(true);return}setBusy(true);if(timer.current)clearTimeout(timer.current);try{await queue.current.catch(()=>{});await api({op:revision?'correct':'submit',task:task.id,answers:latest.current});dirty.current=false;clear();setRecovery(null);setSubmitted(true);setRevision(false);await refresh();setExpanded(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function close(){if(busy)return;setBusy(true);if(timer.current)clearTimeout(timer.current);try{if(dirty.current&&!revision&&!sample)await save();onClose()}catch(e){setError((e as Error).message);setBusy(false)}}
 function startRevision(){setRevision(!sample);setSubmitted(false);setExpanded(true);setSaved(sample?'老师试做，不保存成绩':'修改后请提交订正');if(!sample){const next={...sub?.answers,...sub?.corrections};setAnswers(next);latest.current=next}}
 const content=<div className="reading-workspace" style={{'--reader-size':`${size}px`} as CSSProperties}><AnnotationProvider task={task.id} sample={sample} compact translationEnabled={!sample&&!!sub&&sub.state!=='draft'}>
 <header className="reader-topbar"><button className="reader-back" disabled={busy} onClick={close}><ArrowLeft size={18}/>{sample?'返回题库':'返回作业'}</button><ReaderTools size={size} onSize={()=>setSize(size===22?25:size===25?28:22)} onRead={()=>{setExpanded(false);article.current?.scrollTo({top:0,behavior:'smooth'})}}/><span className="reader-save" role="status">{busy?'正在提交…':reviewing?'已提交':saved} · {done} / {material.questions.length}</span></header>
 <main ref={article} className="reader-article-scroll" aria-label="阅读正文"><article className="reader-article"><span className="tag purple">阅读 · {material.questions[index]?.tag||'理解与表达'}</span><h1>{material.title}</h1>{recovery&&<div className="draft-recovery"><p>发现较新的本机草稿。</p><button className="btn secondary" onClick={()=>{const next=Object.fromEntries(material.questions.map(q=>[q.id,String(recovery.answers[q.id]||'')]));latest.current=next;setAnswers(next);setRevision(recovery.mode==='correction');setSubmitted(false);dirty.current=true;setRecovery(null);setSaved('草稿已恢复，请保存或提交')}}>恢复草稿</button><button className="text-link" onClick={()=>{setRecovery(null);clear()}}>保留服务器版本</button></div>}<div className="reader-prose"><AnnotatedText text={material.body} section="body"/></div><details className="reader-source"><summary>材料来源</summary><p>{material.source||'教师提供'} · {material.rights}</p>{material.sourceUrl&&<a href={material.sourceUrl} target="_blank" rel="noreferrer">查看来源</a>}</details></article></main>
 <section className={'reader-drawer '+(expanded?'expanded':'')} aria-label="阅读题目与作答"><button className="drawer-handle" aria-label={expanded?'收起全部题目':'展开全部题目'} aria-expanded={expanded} onClick={()=>{if(!dragged.current)setExpanded(!expanded)}} onPointerDown={e=>{dragged.current=false;dragY.current=e.clientY;e.currentTarget.setPointerCapture(e.pointerId)}} onPointerUp={e=>{if(dragY.current!==null&&Math.abs(e.clientY-dragY.current)>30){dragged.current=true;setExpanded(e.clientY<dragY.current);e.preventDefault()}dragY.current=null}}><span/></button><div className="drawer-heading"><nav aria-label="选择题号">{material.questions.map((q,i)=><button key={q.id} aria-label={`第 ${i+1} 题${answers[q.id]?.trim()?'，已作答':''}`} aria-current={index===i?'step':undefined} className={index===i?'active':answers[q.id]?.trim()?'answered':''} onClick={()=>{setIndex(i);setExpanded(false)}}>{i+1}</button>)}</nav><button className="drawer-toggle" aria-label={expanded?'收起全部题目':'展开全部题目'} aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>{expanded?<ArrowDown size={16}/>:<ArrowUp size={16}/>}<span>{expanded?'收起全部题目':'展开全部题目'}</span></button><button className="btn" disabled={busy} onClick={reviewing?startRevision:submit}>{reviewing?'开始订正':<><Send size={17}/>{busy?'提交中…':revision?'提交订正':sample?'查看结果':'提交'}</>}</button></div>
 <div className="drawer-content">{error&&<p role="alert" className="error-text">{error}</p>}{material.questions.filter((_,i)=>expanded||i===index).map(q=>{const i=material.questions.indexOf(q);return <section className="reader-question" key={q.id}><h2>{i+1}. <AnnotatedText text={q.prompt} section={'question:'+q.id}/></h2>{q.type==='choice'?<div className="reader-options" role="radiogroup" aria-label={q.prompt}>{q.options.map((option,j)=><label key={option} className={answers[q.id]===option?'selected':''}><input type="radio" name={q.id} value={option} checked={answers[q.id]===option} disabled={reviewing||busy} onChange={()=>change(q.id,option)}/><span>{String.fromCharCode(65+j)}.</span><AnnotatedText text={option} section={`option:${q.id}:${j}`}/>{answers[q.id]===option&&<Check size={17}/>}</label>)}</div>:<textarea aria-label={q.prompt} maxLength={10000} rows={q.type==='writing'?5:2} placeholder="写下你的答案…" value={answers[q.id]||''} disabled={reviewing||busy} onChange={e=>change(q.id,e.target.value)}/>} {reviewing&&q.answer!==undefined&&<div className={'answer-feedback '+(q.type==='writing'?'neutral':correct(q,answers[q.id])?'right':'wrong')}><b>{q.type==='writing'?'参考表达':correct(q,answers[q.id])?'回答正确':'再读一读，看看依据在哪里'}</b><p>{q.answer}</p><p>{q.explanation}</p>{sub?.grades[q.id]!==undefined&&q.type==='writing'&&<p>老师评分：{sub.grades[q.id]} / {q.maxScore||1}</p>}</div>}</section>})}
 {reviewing&&<div className="reader-feedback"><p>{sample?'老师试做不保存成绩。':`首次客观题：${sub?.score||0} / ${sub?.total||0}。订正不会覆盖首次成绩。`}</p>{material.questions.some(q=>q.answer===undefined)&&<p>答案与解析将在老师批改后开放。</p>}{sub?.feedback&&<p className="retell-text">{sub.feedback}</p>}{sub?.unreadFeedback&&<button className="btn secondary" disabled={busy} onClick={async()=>{setBusy(true);try{await api({op:'readFeedback',id:sub.id,version:sub.feedback_updated});await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>我已看过反馈</button>}</div>}
 <div className="reader-question-footer"><span>{done} / {material.questions.length} 已作答</span><div>{!reviewing&&!sample&&!revision&&<button className="text-link" disabled={busy} onClick={()=>save().catch(e=>setError(e.message))}>保存草稿</button>}{!expanded&&index<material.questions.length-1&&<button className="btn secondary" onClick={()=>setIndex(index+1)}>下一题 →</button>}</div></div></div>
 </section></AnnotationProvider></div>;
 return page?content:<Dialog open onOpenChange={open=>{if(!open)close()}}><DialogContent className="reader-preview"><DialogTitle className="sr-only">阅读练习预览</DialogTitle><DialogDescription className="sr-only">阅读正文并完成底部题目，不保存成绩。</DialogDescription>{content}</DialogContent></Dialog>;
}
