import {z} from 'zod';
import {context,sameOrigin,failure,ApiError} from '@/lib/server';
import {ensureVocabulary,vocabularyState,startVocabulary,answerVocabulary,saveVocabularyWord,setVocabularyDaily} from '@/lib/vocabulary-store';
import {wordSchema,sentenceSchema,type WordCard} from '@/lib/vocabulary';
import {aiJson} from '@/lib/ai-client';
export const dynamic='force-dynamic';
export async function GET(req:Request){try{const c=await context();ensureVocabulary();const state=vocabularyState(c.role==='teacher'?c.settings.studentId||'':c.id,c.role==='teacher');const summary=req&&new URL(req.url).searchParams.get('summary')==='1';return Response.json(summary?{day:state.day,dailyNew:state.dailyNew,done:state.done,due:state.due,newAvailable:state.newAvailable,enabledCount:state.enabledCount,pendingNew:state.cards.filter((card:WordCard)=>card.isNew).length,pendingReview:state.cards.filter((card:WordCard)=>!card.isNew).length}:state,{headers:{'Cache-Control':'no-store'}})}catch(e){return failure(e)}}
const payload=z.discriminatedUnion('op',[z.object({op:z.literal('start')}),z.object({op:z.literal('answer'),id:z.string().max(100),choice:z.number().int().min(0).max(3).nullable(),unsure:z.boolean().default(false)}),z.object({op:z.literal('settings'),dailyNew:z.number().int().min(0).max(1000)}),z.object({op:z.literal('save'),word:wordSchema}),z.object({op:z.literal('generate'),word:z.string().min(1).max(80),meaning:z.string().min(1).max(500),contextSentences:z.array(z.object({text:z.string().min(10).max(600),target:z.string().min(1).max(80)})).length(3).optional()})]);
export async function POST(req:Request){try{sameOrigin(req);const c=await context(),p=payload.parse(await req.json());ensureVocabulary();if(p.op==='start'||p.op==='answer'){if(c.role!=='student')throw new ApiError('请在学生账号中完成正式练习',403);return Response.json(p.op==='start'?startVocabulary(c.id):{feedback:answerVocabulary(c.id,p.id,p.choice,p.unsure)})}if(c.role!=='teacher')throw new ApiError('仅教师可以管理词汇',403);if(p.op==='settings')setVocabularyDaily(p.dailyNew);if(p.op==='save')saveVocabularyWord(p.word);if(p.op==='generate'){const result=await aiJson(c.settings,'vocabulary',{word:p.word,meaning:p.meaning,...(p.contextSentences?{contextSentences:p.contextSentences}:{})},'如提供 contextSentences，必须按原顺序逐字保留三个 text 和 target，只补充本句词义、翻译和干扰项，不改写英文原句。返回 {"sentences":[{"text":"英文例句","target":"例句中的目标词或其屈折变化","meaning":"该句中目标词的准确中文释义","translation":"整句中文翻译","distractors":["错误释义1","错误释义2","错误释义3"]}]}。恰好三句不同场景的自然英语，不在句中直接解释目标词；四个中文释义互不重复，且只有一个与语境相符。').catch(e=>{throw new ApiError(e instanceof Error?e.message:'AI 服务暂时不可用',502)});const sentences=z.array(sentenceSchema).length(3).parse(result.sentences);if(p.contextSentences&&sentences.some((s,i)=>s.text!==p.contextSentences![i].text||s.target!==p.contextSentences![i].target))throw new ApiError('AI 改写了导入的原句，请重试',502);if(new Set(sentences.map(s=>s.text.toLowerCase())).size!==3)throw new ApiError('生成的例句重复，请重试');return Response.json({sentences})}return Response.json({ok:true})}catch(e){if(e instanceof z.ZodError)return Response.json({error:e.issues.map(i=>i.message).join('；')},{status:400});return failure(e)}}
