import { sqliteTable, text, integer, uniqueIndex, index, primaryKey } from 'drizzle-orm/sqlite-core';
export const settings = sqliteTable('settings', { id: integer('id').primaryKey(), owner: text('owner').notNull(), data: text('data').notNull() });
export const messages=sqliteTable('messages',{id:integer('id').primaryKey({autoIncrement:true}),student:text('student').notNull().references(()=>accounts.id),author:text('author').notNull(),body:text('body').notNull(),created:text('created').notNull(),readAt:text('read_at')},t=>[index('idx_messages_student').on(t.student,t.id)]);
export const materials = sqliteTable('materials', { id: text('id').primaryKey(), data: text('data').notNull(), created: text('created').notNull() });
export const tasks = sqliteTable('tasks', { id: text('id').primaryKey(), date: text('date').notNull(), material: text('material').notNull(), note: text('note').notNull(), created: text('created').notNull() }, t=>[index('idx_tasks_date').on(t.date)]);
export const submissions = sqliteTable('submissions', { id: text('id').primaryKey(), task: text('task').notNull().references(()=>tasks.id), student: text('student').notNull(), answers: text('answers').notNull(), state: text('state').notNull(), score: integer('score').notNull(), total: integer('total').notNull(), feedback: text('feedback').notNull(), feedbackUpdated:text('feedback_updated').notNull().default(''), feedbackRead:text('feedback_read').notNull().default(''), correctionStatus:text('correction_status').notNull().default(''), grades: text('grades').notNull(), corrections: text('corrections').notNull(), submitted: text('submitted'), updated: text('updated').notNull() }, t=>[uniqueIndex('idx_submissions_task_student').on(t.task,t.student),index('idx_submissions_student').on(t.student)]);
export const accounts=sqliteTable('accounts',{id:text('id').primaryKey(),username:text('username').notNull(),role:text('role').notNull(),passwordHash:text('password_hash').notNull(),created:text('created').notNull()},t=>[uniqueIndex('idx_accounts_username').on(t.username),uniqueIndex('idx_accounts_role').on(t.role)]);
export const sessions=sqliteTable('sessions',{tokenHash:text('token_hash').primaryKey(),accountId:text('account_id').notNull().references(()=>accounts.id),expires:integer('expires').notNull()},t=>[index('idx_sessions_account').on(t.accountId),index('idx_sessions_expiry').on(t.expires)]);
export const authLimits=sqliteTable('auth_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expires:integer('expires').notNull()},t=>[index('idx_auth_limits_expiry').on(t.expires)]);
export const listens=sqliteTable('listens',{id:text('id').primaryKey(),task:text('task').notNull().references(()=>tasks.id),student:text('student').notNull(),count:integer('count').notNull().default(0),extra:integer('extra').notNull().default(0),token:text('token'),expires:integer('expires').notNull().default(0)},t=>[uniqueIndex('idx_listens_task_student').on(t.task,t.student)]);
export const assessments=sqliteTable('assessments',{id:text('id').primaryKey(),submission:text('submission').notNull().references(()=>submissions.id),question:text('question').notNull(),state:text('state').notNull(),data:text('data').notNull().default('{}'),attempts:integer('attempts').notNull().default(0),updated:integer('updated').notNull()},t=>[uniqueIndex('idx_assessments_submission_question').on(t.submission,t.question)]);
export const annotations=sqliteTable('annotations',{id:text('id').primaryKey(),student:text('student').notNull(),task:text('task').notNull().references(()=>tasks.id),section:text('section').notNull(),start:integer('start').notNull(),end:integer('end').notNull(),text:text('text').notNull(),kind:text('kind').notNull(),note:text('note').notNull().default(''),created:text('created').notNull(),updated:text('updated').notNull()},t=>[uniqueIndex('idx_annotations_selection').on(t.student,t.task,t.section,t.start,t.end),index('idx_annotations_task').on(t.task)]);
export const cultureProgress=sqliteTable('culture_progress',{id:text('id').primaryKey(),material:text('material').notNull().references(()=>materials.id),student:text('student').notNull(),data:text('data').notNull().default('{}'),updated:text('updated').notNull()},t=>[uniqueIndex('idx_culture_progress_material_student').on(t.material,t.student),index('idx_culture_progress_student').on(t.student)]);

export const vocabularySettings=sqliteTable('vocabulary_settings',{id:integer('id').primaryKey(),dailyNew:integer('daily_new').notNull().default(8),seedVersion:integer('seed_version').notNull().default(0)});
export const vocabularyWords=sqliteTable('vocabulary_words',{id:text('id').primaryKey(),data:text('data').notNull(),position:integer('position').notNull(),enabled:integer('enabled').notNull().default(0),updated:text('updated').notNull()});
export const vocabularyProgress=sqliteTable('vocabulary_progress',{student:text('student').notNull(),word:text('word').notNull().references(()=>vocabularyWords.id),nextDue:text('next_due').notNull(),streak:integer('streak').notNull().default(0),reviews:integer('reviews').notNull().default(0),lapses:integer('lapses').notNull().default(0),lastDay:text('last_day').notNull()},t=>[primaryKey({columns:[t.student,t.word]}),index('idx_vocabulary_due').on(t.student,t.nextDue)]);
export const vocabularyAttempts=sqliteTable('vocabulary_attempts',{id:text('id').primaryKey(),student:text('student').notNull(),word:text('word').notNull().references(()=>vocabularyWords.id),day:text('day').notNull(),isNew:integer('is_new').notNull(),snapshot:text('snapshot').notNull(),result:text('result'),created:text('created').notNull()},t=>[uniqueIndex('idx_vocabulary_once_daily').on(t.student,t.word,t.day),index('idx_vocabulary_day').on(t.student,t.day)]);
