import {z} from 'zod';
import {context,db,ApiError,failure,sameOrigin} from '@/lib/server';
import type {Material} from '@/lib/course';
export const dynamic='force-dynamic';

const payload=z.object({material:z.string().min(1).max(100),step:z.enum(['explore','learn','check','express']).optional(),answers:z.record(z.string().max(80),z.string().max(500)).optional(),expression:z.string().max(10000).optional()});
function decode(row:any){if(!row)return null;try{return {...JSON.parse(row.data),updated:row.updated}}catch{return null}}

export async function GET(req:Request){try{const c=await context();if(c.role!=='student')return Response.json({progress:{}});const id=new URL(req.url).searchParams.get('material');if(id){const row=await db().prepare('SELECT data,updated FROM culture_progress WHERE material=? AND student=?').bind(id,c.id).first();return Response.json({progress:decode(row)},{headers:{'Cache-Control':'no-store'}})}const rows=await db().prepare('SELECT material,data,updated FROM culture_progress WHERE student=?').bind(c.id).all();return Response.json({progress:Object.fromEntries(rows.results.map((r:any)=>[r.material,decode(r)]))},{headers:{'Cache-Control':'no-store'}})}catch(e){return failure(e)}}

export async function POST(req:Request){try{sameOrigin(req);const c=await context();if(c.role!=='student')throw new ApiError('仅学生可以保存文化学习进度',403);const p=payload.parse(await req.json()),row=await db().prepare('SELECT data FROM materials WHERE id=?').bind(p.material).first();if(!row)throw new ApiError('文化主题不存在',404);const material=JSON.parse(row.data) as Material,cfg=material.cultureConfig;if(material.kind!=='知识拓展'||!material.reviewed||!cfg)throw new ApiError('文化主题尚未开放',404);const current=decode(await db().prepare('SELECT data,updated FROM culture_progress WHERE material=? AND student=?').bind(p.material,c.id).first())||{steps:[],answers:{},expression:'',score:0,status:'未开始'};const answers={...current.answers,...Object.fromEntries(Object.entries(p.answers||{}).filter(([id])=>cfg.checkQuestions.some(q=>q.id===id)))},expression=p.expression===undefined?current.expression:p.expression,steps=[...new Set([...(current.steps||[]),...(p.step?[p.step]:[])])];const answered=cfg.checkQuestions.filter(q=>answers[q.id]),results=Object.fromEntries(cfg.checkQuestions.map(q=>[q.id,answers[q.id]===q.answer])),correct=Object.values(results).filter(Boolean).length,score=cfg.checkQuestions.length?Math.round(correct/cfg.checkQuestions.length*100):0,status=answered.length===cfg.checkQuestions.length&&score>=80&&expression.trim()?'已完成':steps.length||answered.length||expression.trim()?'学习中':'未开始',data={steps,answers,expression,score,status,answered:answered.length,total:cfg.checkQuestions.length,results};const now=new Date().toISOString();await db().prepare('INSERT INTO culture_progress(id,material,student,data,updated) VALUES(?,?,?,?,?) ON CONFLICT(material,student) DO UPDATE SET data=excluded.data,updated=excluded.updated').bind(crypto.randomUUID(),p.material,c.id,JSON.stringify(data),now).run();return Response.json({progress:{...data,updated:now}})}catch(e){if(e instanceof z.ZodError)return Response.json({error:'请检查学习记录：'+e.issues.map(i=>i.message).join('；')},{status:400});return failure(e)}}
